version: '3.7'

services:
  db:
    image: edoburu/pgbouncer:1.15.0
    environment:
      - DB_HOST=pg
    env_file:
      - ./.env.prod
    depends_on:
      - pg
  pg:
    build: ./services/pg
    command: postgres -c config_file=/etc/postgresql.conf
    #volumes:
        # - postgres_fastdata:/fastdata
        # - postgres_wal:/var/lib/postgresql/data/pg_wal/
        # - /data/volumes/novichenko_18jan:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

networks:
  default:
    name: novichenko

#volumes:
#  postgres_fastdata:
